### ISSUE TITLE
Turning off the "display names" option doesn't work

### ISSUE THREAD

**Issue by nicosensei** [sreichholf/repola#2]
Hi,

I've discovered your launcher recently and I enjoy it on both my Retroid Pocket 2 and Powkiddy X18.

I believe I found an issue. If I turn off the "display names" option in the launcher settings, labels are still displayed below the icons.

**Comment by hh3k0** [comment]
I'm experiencing the same issue on my Retroid Pocket 2, using LineageOS 15.1 (and the bundled RePoLa).

**Comment by sabre230** [comment]
I also have this issue.

**Comment by sreichholf** [comment]
This is now fixed in v1.4.0.
See https://github.com/sreichholf/repola/releases for more details
