### ISSUE TITLE
Installed apps not listed

### ISSUE THREAD

**Issue by DMscotifer** [sreichholf/repola#3]
Installed on a Oneplus 7 Pro running Android 11. 

![Screenshot_20220226-101036_RePoLa](https://user-images.githubusercontent.com/25377671/155837435-9e2afd34-f235-4074-aa06-3a71b133babf.png)

Limited app selection. Not sure if there is maybe some permission issue? Otherwise, it appears to be fully functional.

**Comment by daylerees** [comment]
Hi there, this launcher looks fantastic, however I'm having a similar problem on a Retroid Pocket 3 - I see a similar limited app collection.

**Comment by sreichholf** [comment]
I guess we REALLY need a new release, right? :)
I'll have a look today, maybe this can be done on short notice

**Comment by sreichholf** [comment]
OK.
I've just upped v1.4.0 which should adress all of the issues related to android >= 11 like missing apps.
See https://github.com/sreichholf/repola/releases for more details

**Comment by daylerees** [comment]
Oh woah! Thanks @sreichholf  - as someone who struggles to maintain his own repos I'm deeply thankful for your turnaround here. There's a void of aesthetically pleasing android launchers, and this is one of the best I've seen for console environments. Thanks for looking at this! I'll test this later today. :)

**Comment by daylerees** [comment]
It works great, thanks for the update!
